"""initial migration

Revision ID: 3e4f93ef1ab6
Revises:
Create Date: 2017-01-29 02:19:53.973816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4f93ef1ab6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('sqlite_sequence')
    op.create_unique_constraint(None, 'athlima', ['lektiko'])
    op.alter_column('athlima_greeklish', 'athlima_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_unique_constraint(None, 'athlima_greeklish', ['lektiko'])
    op.create_foreign_key(None, 'athlima_greeklish', 'athlima', ['athlima_id'], ['id'])
    op.create_unique_constraint(None, 'mousiko_organo', ['lektiko'])
    op.alter_column('mousiko_organo_greeklish', 'mousiko_organo_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_unique_constraint(None, 'mousiko_organo_greeklish', ['lektiko'])
    op.create_foreign_key(None, 'mousiko_organo_greeklish', 'mousiko_organo', ['mousiko_organo_id'], ['id'])
    op.create_unique_constraint(None, 'perioxh', ['lektiko'])
    op.alter_column('perioxh_greeklish', 'perioxh_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_unique_constraint(None, 'perioxh_greeklish', ['lektiko'])
    op.create_foreign_key(None, 'perioxh_greeklish', 'perioxh', ['perioxh_id'], ['id'])
    op.alter_column('pinakas', 'athlima_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pinakas', 'mousiko_organo_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pinakas', 'perioxh_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pinakas', 'smeae_kathgoria_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pinakas', 'smeae_pinakas_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_unique_constraint(None, 'pinakas', ['url_pinaka'])
    op.create_foreign_key(None, 'pinakas', 'kathgoria', ['kathgoria_id'], ['kathgoria_id'])
    op.create_foreign_key(None, 'pinakas', 'sxoliko_etos', ['sxoliko_etos_id'], ['sxoliko_etos_id'])
    op.create_foreign_key(None, 'pinakas', 'perioxh', ['perioxh_id'], ['id'])
    op.create_foreign_key(None, 'pinakas', 'smeae_kathgoria', ['smeae_kathgoria_id'], ['id'])
    op.create_foreign_key(None, 'pinakas', 'smeae_pinakas', ['smeae_pinakas_id'], ['id'])
    op.create_foreign_key(None, 'pinakas', 'mousiko_organo', ['mousiko_organo_id'], ['id'])
    op.create_foreign_key(None, 'pinakas', 'athlima', ['athlima_id'], ['id'])
    op.create_foreign_key(None, 'pinakas', 'hmeromhnia', ['hmeromhnia_id'], ['hmeromhnia_id'])
    op.create_unique_constraint(None, 'smeae_kathgoria', ['lektiko'])
    op.alter_column('smeae_kathgoria_greeklish', 'smeae_kathgoria_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_unique_constraint(None, 'smeae_kathgoria_greeklish', ['lektiko'])
    op.create_foreign_key(None, 'smeae_kathgoria_greeklish', 'smeae_kathgoria', ['smeae_kathgoria_id'], ['id'])
    op.alter_column('smeae_pinakas', 'lektiko',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'smeae_pinakas', ['lektiko'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'smeae_pinakas', type_='unique')
    op.alter_column('smeae_pinakas', 'lektiko',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'smeae_kathgoria_greeklish', type_='foreignkey')
    op.drop_constraint(None, 'smeae_kathgoria_greeklish', type_='unique')
    op.alter_column('smeae_kathgoria_greeklish', 'smeae_kathgoria_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'smeae_kathgoria', type_='unique')
    op.drop_constraint(None, 'pinakas', type_='foreignkey')
    op.drop_constraint(None, 'pinakas', type_='foreignkey')
    op.drop_constraint(None, 'pinakas', type_='foreignkey')
    op.drop_constraint(None, 'pinakas', type_='foreignkey')
    op.drop_constraint(None, 'pinakas', type_='foreignkey')
    op.drop_constraint(None, 'pinakas', type_='foreignkey')
    op.drop_constraint(None, 'pinakas', type_='foreignkey')
    op.drop_constraint(None, 'pinakas', type_='foreignkey')
    op.drop_constraint(None, 'pinakas', type_='unique')
    op.alter_column('pinakas', 'smeae_pinakas_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pinakas', 'smeae_kathgoria_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pinakas', 'perioxh_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pinakas', 'mousiko_organo_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pinakas', 'athlima_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'perioxh_greeklish', type_='foreignkey')
    op.drop_constraint(None, 'perioxh_greeklish', type_='unique')
    op.alter_column('perioxh_greeklish', 'perioxh_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'perioxh', type_='unique')
    op.drop_constraint(None, 'mousiko_organo_greeklish', type_='foreignkey')
    op.drop_constraint(None, 'mousiko_organo_greeklish', type_='unique')
    op.alter_column('mousiko_organo_greeklish', 'mousiko_organo_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'mousiko_organo', type_='unique')
    op.drop_constraint(None, 'athlima_greeklish', type_='foreignkey')
    op.drop_constraint(None, 'athlima_greeklish', type_='unique')
    op.alter_column('athlima_greeklish', 'athlima_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'athlima', type_='unique')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
