version: '3'

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:80
        --access-logfile -
        --reload
        "app:create_app('testing')"
    env_file:
      - '.env'
    volumes:
      - '.:/talaiporosanaplirotis'
    ports:
      - '80:80'
